spring:
  profiles: testQivos
name: testQivosYAML
environment: test
genderApiConf:
  baseUrl: https://gender-api.com
  nameOnlyReq: /get
  apiKey: hTYoDhotyWJmDJjDRs
helperWSConf:
  baseUrl: http://localhost:8081
  numberizer: /Numberizer
  numMatcher: /NumMatcher

---

spring:
  profiles: dockerTest
name: dockerTestYAML
environment: docker
genderApiConf:
  baseUrl: https://gender-api.com
  nameOnlyReq: /get
  apiKey: hTYoDhotyWJmDJjDRs
helperWSConf:
  baseUrl: http://cp-perfectmatchhelper-nodejs:8081
  numberizer: /Numberizer
  numMatcher: /NumMatcher
